[project]
name = "fastapi-backend-starter"
version = "0.1.0"
description = "Production-ready FastAPI starter template"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Amal Das", email = "amaldas@interloid.com" }
]

dependencies = [
    "fastapi>=0.141.1",
    "uvicorn>=0.35.0",
    "pydantic-settings>=2.14.2",
    "python-dotenv>=1.2.2",
    "beanie >= 2.1.0",
    "motor>=3.7.1",
    "pymongo>=4.13.2",
    "pwdlib[argon2]>=0.3.0",
    "python-jose[cryptography]>=3.5.0",
]

[dependency-groups]
dev = [
    "ruff>=0.16.1",
]

[tool.hatch.build.targets.wheel]
packages = ["app"]

[tool.ruff]
line-length = 88
target-version = "py312"

exclude = [
    "migrations/versions",
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "UP",
] 

ignore = [
    "UP046",
]  

[tool.pytest.ini_options]
testpaths = ["tests"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
